version: '3.1'

volumes:
  db-data:

services:
  db:
    image: mysql:8.0.12
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql
