version: '3.1'

volumes:
  db-data:

services:
  db:
    image: mysql:8.0.12
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - db-data:/var/lib/mysql

  app:
    image: messenger:1
    environment:
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASS: root
